services:
  web:
    build: docker/
    container_name: go_recommendation_consumer
    volumes:
      - .:/app
      - /app/bin
    environment:
      - APP_ENV=development
      - ROOT_DIR=/app
    depends_on:
      - db
    networks:
      default:
  db:
    image: postgres
    restart: always
    container_name: go_recommendation_postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
    networks:
      default:
volumes:
  db-data:
  rabbitmq-data:

networks:
  default:
      name: grpc-network
      external: true