services:
  web:
    build: docker/
    container_name: go_recommendation_consumer
    volumes:
      - .:/app
      - /app/bin
      - ./sqlite-data:${SQLITE_PATH}
    environment:
      - APP_ENV=development
      - ROOT_DIR=/app
    networks:
      default:
volumes:
  sqlite-data:

networks:
  default:
      name: grpc-network
      external: true