name: Run Tests

on: push

jobs:

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Install dependencies
      run: go mod download
    - name: Set up SQLite database
      run: |
        mkdir -p data
        touch data/go_recommendation_test.sqlite3
    - name: Set up RabbitMQ
      run: |
        docker run -d --name rabbitmq -p 5672:5672 \
          -e RABBITMQ_DEFAULT_USER=guest \
          -e RABBITMQ_DEFAULT_PASS=guest \
          --health-cmd "rabbitmqctl status" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 3 \
          rabbitmq:3
    - name: Wait for RabbitMQ
      run: |
        echo "Waiting for RabbitMQ to be ready..."
        for i in {1..10}; do
          if nc -z localhost 5672; then
            echo "RabbitMQ is ready!"
            break
          fi
          echo "RabbitMQ is not ready yet. Retrying in 5 seconds..."
          sleep 5
        done
    - name: Test and code coverage
      env:
        APP_ENV: test
        ROOT_DIR: /home/runner/work/go-recommendation/go-recommendation
        SQLITE_PATH: /home/runner/work/go-recommendation/go-recommendation/data
        SQLITE_DB_NAME: go_recommendation_test.sqlite3
      run: |
        go test -v ./tests
        chmod +x scripts/coverage.sh
        scripts/coverage.sh
    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage/filtered_coverage.out
